trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

 # - script: dotnet test -c release --logger trx
 #   displayName: 'dotnet test'

 # - task: PublishTestResults@2
 #   condition: succeededOrFailed()
 #   inputs:
 #    testRunner: VSTest
 #    testResultsFiles: '**/*.trx'

 - script: dotnet build ShiftBlazor --configuration release
   displayName: 'dotnet build'

 - script: dotnet pack ShiftBlazor --configuration release --output $(Build.ArtifactStagingDirectory)
   displayName: 'dotnet pack'

 - task: NuGetCommand@2
   condition: contains(variables['Build.SourceBranch'], 'refs/tags/release') 
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'