//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSoftware.ShiftBlazor.Resources.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShiftList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSoftware.ShiftBlazor.Resources.Components.ShiftList", typeof(ShiftList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ActionsColumnHeaderText {
            get {
                return ResourceManager.GetString("ActionsColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddNewItemTitle {
            get {
                return ResourceManager.GetString("AddNewItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseModalButtonTitle {
            get {
                return ResourceManager.GetString("CloseModalButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide or Show Columns.
        /// </summary>
        internal static string ColumnChooserTitle {
            get {
                return ResourceManager.GetString("ColumnChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as CSV.
        /// </summary>
        internal static string ExportButtonTitle {
            get {
                return ResourceManager.GetString("ExportButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter deleted items.
        /// </summary>
        internal static string FilterDeletedItemsTitle {
            get {
                return ResourceManager.GetString("FilterDeletedItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string GridItemsLoadingText {
            get {
                return ResourceManager.GetString("GridItemsLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IdColumnHeaderText {
            get {
                return ResourceManager.GetString("IdColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Deleted.
        /// </summary>
        internal static string IsDeletedColumnHeaderText {
            get {
                return ResourceManager.GetString("IsDeletedColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        internal static string ItemsPerPageLabel {
            get {
                return ResourceManager.GetString("ItemsPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListDefaultTitle {
            get {
                return ResourceManager.GetString("ListDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found..
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t access ({0}).
        /// </summary>
        internal static string ReadAccessDenied {
            get {
                return ResourceManager.GetString("ReadAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string RefreshList {
            get {
                return ResourceManager.GetString("RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAllButtonTitle {
            get {
                return ResourceManager.GetString("SelectAllButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} selected.
        /// </summary>
        internal static string SelectedItemsCounterLabel {
            get {
                return ResourceManager.GetString("SelectedItemsCounterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Active Only.
        /// </summary>
        internal static string ShowActiveOnlyOption {
            get {
                return ResourceManager.GetString("ShowActiveOnlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string ShowBothDeletedAndActiveOption {
            get {
                return ResourceManager.GetString("ShowBothDeletedAndActiveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Deleted Only.
        /// </summary>
        internal static string ShowDeletedOnlyOption {
            get {
                return ResourceManager.GetString("ShowDeletedOnlyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewItemButtonText {
            get {
                return ResourceManager.GetString("ViewItemButtonText", resourceCulture);
            }
        }
    }
}
