//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftSoftware.ShiftBlazor.Resources.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShiftList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShiftSoftware.ShiftBlazor.Resources.Components.ShiftList", typeof(ShiftList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create action button.
        /// </summary>
        internal static string ActionButtonError {
            get {
                return ResourceManager.GetString("ActionButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ActionsColumnTitle {
            get {
                return ResourceManager.GetString("ActionsColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ColumnChooser {
            get {
                return ResourceManager.GetString("ColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Export.
        /// </summary>
        internal static string CSVExportButton {
            get {
                return ResourceManager.GetString("CSVExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initiate download action.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export.
        /// </summary>
        internal static string ExcelExportButton {
            get {
                return ResourceManager.GetString("ExcelExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter deleted items.
        /// </summary>
        internal static string FilterDeletedItems {
            get {
                return ResourceManager.GetString("FilterDeletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting list of items.
        /// </summary>
        internal static string GetItemListError {
            get {
                return ResourceManager.GetString("GetItemListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        internal static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string IdColumnHeaderText {
            get {
                return ResourceManager.GetString("IdColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        internal static string ItemsPerPageLabel {
            get {
                return ResourceManager.GetString("ItemsPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListDefaultTitle {
            get {
                return ResourceManager.GetString("ListDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} pages ({2} items).
        /// </summary>
        internal static string PageCountAndTotal {
            get {
                return ResourceManager.GetString("PageCountAndTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Export.
        /// </summary>
        internal static string PDFExportButton {
            get {
                return ResourceManager.GetString("PDFExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintButton {
            get {
                return ResourceManager.GetString("PrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initiate print action.
        /// </summary>
        internal static string PrintFailed {
            get {
                return ResourceManager.GetString("PrintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Print Window, this might take a while.
        /// </summary>
        internal static string PrintMessage {
            get {
                return ResourceManager.GetString("PrintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t access ({0}).
        /// </summary>
        internal static string ReadAccessDenied {
            get {
                return ResourceManager.GetString("ReadAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string RefreshList {
            get {
                return ResourceManager.GetString("RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Items.
        /// </summary>
        internal static string SelectedItemsCounterLabel {
            get {
                return ResourceManager.GetString("SelectedItemsCounterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Active Only.
        /// </summary>
        internal static string ShowActiveOnly {
            get {
                return ResourceManager.GetString("ShowActiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string ShowBothDeletedAndActive {
            get {
                return ResourceManager.GetString("ShowBothDeletedAndActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Deleted Only.
        /// </summary>
        internal static string ShowDeletedOnly {
            get {
                return ResourceManager.GetString("ShowDeletedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items.
        /// </summary>
        internal static string TotalItemsLabel {
            get {
                return ResourceManager.GetString("TotalItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }
    }
}
